[package]
org = "ballerinax"
name = "aws.redshiftdata"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["Data Warehouse", "Columnar Storage", "Cost/Paid", "vendor/aws"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.redshiftdata"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.9.0"

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "aws.redshiftdata-native"
version = "0.1.0-SNAPSHOT"
path = "../native/build/libs/aws.redshiftdata-native-0.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "redshiftdata"
version = "2.27.21"
path = "./lib/redshiftdata-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "apache-client"
version = "2.27.21"
path = "./lib/apache-client-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "protocol-core"
version = "2.27.21"
path = "./lib/protocol-core-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "aws-json-protocol"
version = "2.27.21"
path = "./lib/aws-json-protocol-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth-aws"
version = "2.27.21"
path = "./lib/http-auth-aws-2.27.21.jar"
