[package]
org = "ballerinax"
name = "aws.redshiftdata"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["Data Warehouse", "Columnar Storage", "Cost/Paid", "vendor/aws"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.redshiftdata"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.2"

[[platform.java11.dependency]]
groupId = "io.ballerina.lib"
artifactId = "aws.redshiftdata-native"
version = "0.1.0-SNAPSHOT"
path = "../native/build/libs/aws.redshiftdata-native-0.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "annotations"
version = "2.27.21"
path = "./lib/annotations-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "apache-client"
version = "2.27.21"
path = "./lib/apache-client-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "auth"
version = "2.27.21"
path = "./lib/auth-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "aws-core"
version = "2.27.21"
path = "./lib/aws-core-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "aws-json-protocol"
version = "2.27.21"
path = "./lib/aws-json-protocol-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "aws-query-protocol"
version = "2.27.21"
path = "./lib/aws-query-protocol-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "checksums"
version = "2.27.21"
path = "./lib/checksums-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "checksums-spi"
version = "2.27.21"
path = "./lib/checksums-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "commons-codec"
artifactId = "commons-codec"
version = "1.17.1"
path = "./lib/commons-codec-1.17.1.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "endpoints-spi"
version = "2.27.21"
path = "./lib/endpoints-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "eventstream"
version = "1.0.1"
path = "./lib/eventstream-1.0.1.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth"
version = "2.27.21"
path = "./lib/http-auth-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth-aws"
version = "2.27.21"
path = "./lib/http-auth-aws-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth-aws-eventstream"
version = "2.27.21"
path = "./lib/http-auth-aws-eventstream-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth-spi"
version = "2.27.21"
path = "./lib/http-auth-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-client-spi"
version = "2.27.21"
path = "./lib/http-client-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "org.apache.httpcomponents"
artifactId = "httpclient"
version = "4.5.13"
path = "./lib/httpclient-4.5.13.jar"

[[platform.java17.dependency]]
groupId = "org.apache.httpcomponents"
artifactId = "httpcore"
version = "4.4.16"
path = "./lib/httpcore-4.4.16.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "identity-spi"
version = "2.27.21"
path = "./lib/identity-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "json-utils"
version = "2.27.21"
path = "./lib/json-utils-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "metrics-spi"
version = "2.27.21"
path = "./lib/metrics-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.112.Final"
path = "./lib/netty-buffer-4.1.112.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.1.112.Final"
path = "./lib/netty-codec-4.1.112.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "4.1.112.Final"
path = "./lib/netty-codec-http-4.1.112.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http2"
version = "4.1.112.Final"
path = "./lib/netty-codec-http2-4.1.112.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.112.Final"
path = "./lib/netty-common-4.1.112.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.112.Final"
path = "./lib/netty-handler-4.1.112.Final.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "netty-nio-client"
version = "2.27.21"
path = "./lib/netty-nio-client-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.112.Final"
path = "./lib/netty-resolver-4.1.112.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.112.Final"
path = "./lib/netty-transport-4.1.112.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-classes-epoll"
version = "4.1.112.Final"
path = "./lib/netty-transport-classes-epoll-4.1.112.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-unix-common"
version = "4.1.112.Final"
path = "./lib/netty-transport-native-unix-common-4.1.112.Final.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "profiles"
version = "2.27.21"
path = "./lib/profiles-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "protocol-core"
version = "2.27.21"
path = "./lib/protocol-core-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "org.reactivestreams"
artifactId = "reactive-streams"
version = "1.0.4"
path = "./lib/reactive-streams-1.0.4.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "redshift"
version = "2.27.21"
path = "./lib/redshift-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "redshiftdata"
version = "2.27.21"
path = "./lib/redshiftdata-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "regions"
version = "2.27.21"
path = "./lib/regions-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "retries"
version = "2.27.21"
path = "./lib/retries-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "retries-spi"
version = "2.27.21"
path = "./lib/retries-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "sdk-core"
version = "2.27.21"
path = "./lib/sdk-core-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-api"
version = "1.7.36"
path = "./lib/slf4j-api-1.7.36.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "sql-native"
version = "1.13.3"
path = "./lib/sql-native-1.13.3.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "third-party-jackson-core"
version = "2.27.21"
path = "./lib/third-party-jackson-core-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "utils"
version = "2.27.21"
path = "./lib/utils-2.27.21.jar"
