[package]
org = "ballerinax"
name = "aws.redshiftdata"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["Data Warehouse", "Columnar Storage", "Cost/Paid", "vendor/aws"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.redshiftdata"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.9.0"

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "aws.redshiftdata-native"
version = "0.1.0-SNAPSHOT"
path = "../native/build/libs/aws.redshiftdata-native-0.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "redshiftdata"
version = "2.27.21"
path = "./lib/redshiftdata-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "apache-client"
version = "2.27.21"
path = "./lib/apache-client-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "auth"
version = "2.27.21"
path = "./lib/auth-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "aws-core"
version = "2.27.21"
path = "./lib/aws-core-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "endpoints-spi"
version = "2.27.21"
path = "./lib/endpoints-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth"
version = "2.27.21"
path = "./lib/http-auth-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth-aws"
version = "2.27.21"
path = "./lib/http-auth-aws-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-auth-spi"
version = "2.27.21"
path = "./lib/http-auth-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "http-client-spi"
version = "2.27.21"
path = "./lib/http-client-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "identity-spi"
version = "2.27.21"
path = "./lib/identity-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "profiles"
version = "2.27.21"
path = "./lib/profiles-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "regions"
version = "2.27.21"
path = "./lib/regions-2.27.21.jar"

# [[platform.java17.dependency]]
# groupId = "software.amazon.awssdk"
# artifactId = "retries"
# version = "2.27.21"
# path = "./lib/retries-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "retries-spi"
version = "2.27.21"
path = "./lib/retries-spi-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "sdk-core"
version = "2.27.21"
path = "./lib/sdk-core-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "software.amazon.awssdk"
artifactId = "utils"
version = "2.27.21"
path = "./lib/utils-2.27.21.jar"

[[platform.java17.dependency]]
groupId = "org.reactivestreams"
artifactId = "reactive-streams"
version = "1.0.4"
path = "./lib/reactive-streams-1.0.4.jar"
