[package]
org = "ballerinax"
name = "aws.redshiftdata"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["Data Warehouse", "Columnar Storage", "Cost/Paid", "vendor/aws"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.redshiftdata"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.2"

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "aws.redshiftdata-native"
version = "0.1.0-SNAPSHOT"
path = "../native/build/libs/aws.redshiftdata-native-0.1.0-SNAPSHOT.jar"
