name: GraalVM Check

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  call_stdlib_workflow:
    name: Run StdLib Workflow
    if: ${{ github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository_owner == 'ballerina-platform') }}
    uses: ballerina-platform/ballerina-library/.github/workflows/build-with-bal-test-graalvm-connector-template.yml@2201.10.x
    secrets: inherit
    with:
      additional-build-flags: "-x test"
      # Adding a test group for `mockServer` to disable the tests, as we don't have a live redshift-data instance to run tests against 
      additional-test-flags: "--groups mockServer"
